### ISSUE TITLE
Fix #[cfg(cargo_ligen)] test

### ISSUE THREAD

**Issue by notdanilo** [sensorial-systems/ligen-c#17]
This isn't working, because only `cargo ligen` sets this up https://github.com/sensorial-systems/ligen-c/blob/cd40a6c978c9b02e0260d0ce5738361fca01af3a/macro/tests/externs.rs#L27

**Comment by arrudagates** [comment]
This is missing an `use` line, `use super::*;` should do the trick
https://github.com/sensorial-systems/ligen-c/blob/cd40a6c978c9b02e0260d0ce5738361fca01af3a/macro/tests/externs.rs#L29

**Comment by arrudagates** [comment]
And then it can be tested using the `cargo ligen test` command from [this PR](https://github.com/sensorial-systems/cargo-ligen/pull/9)
